name: Upload to Gemfury

on:
  release:
    types: [published]
  workflow_dispatch:  # This allows you to click "Run workflow" manually

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload to Gemfury
        env:
          FURY_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
        run: |
          # The -f flag in curl makes it fail the step if the server returns an error
          for file in dist/*; do
            echo "Uploading $file..."
            curl -f -F package=@$file https://$FURY_TOKEN@push.fury.io/dhp5621/
          done
